// @flow

export const moduleName: string = "signIn";

export const SIGN_IN_REQUEST: "SIGN_IN/SIGN_IN_REQUEST" = "SIGN_IN/SIGN_IN_REQUEST";
export const SIGN_IN_START: "SIGN_IN/SIGN_IN_START" = "SIGN_IN/SIGN_IN_START";
export const SIGN_IN_SUCCESS: "SIGN_IN/SIGN_IN_SUCCESS" = "SIGN_IN/SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL: "SIGN_IN/SIGN_IN_FAIL" = "SIGN_IN/SIGN_IN_FAIL";
