// @flow

export const moduleName: string = "auth";

export const FETCH_USER_INFO_REQUEST: "AUTH/FETCH_USER_INFO_REQUEST" = "AUTH/FETCH_USER_INFO_REQUEST";
export const FETCH_USER_INFO_START: "AUTH/FETCH_USER_INFO_START" = "AUTH/FETCH_USER_INFO_START";
export const FETCH_USER_INFO_SUCCESS: "AUTH/FETCH_USER_INFO_SUCCESS" = "AUTH/FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAIL: "AUTH/FETCH_USER_INFO_FAIL" = "AUTH/FETCH_USER_INFO_FAIL";

export const TOKEN_REFRESH_REQUEST: "AUTH/TOKEN_REFRESH_REQUEST" = "AUTH/TOKEN_REFRESH_REQUEST";
export const TOKEN_REFRESH_START: "AUTH/TOKEN_REFRESH_START" = "AUTH/TOKEN_REFRESH_START";
export const TOKEN_REFRESH_SUCCESS: "AUTH/TOKEN_REFRESH_SUCCESS" = "AUTH/TOKEN_REFRESH_SUCCESS";
export const TOKEN_REFRESH_FAIL: "AUTH/TOKEN_REFRESH_FAIL" = "AUTH/TOKEN_REFRESH_FAIL";

// When we need to sec silent refresh on client
export const SILENT_REFRESH_TO_SET: "AUTH/SILENT_REFRESH_TO_SET" = "AUTH/SILENT_REFRESH_TO_SET";
// Sets silent refresh
export const SET_SILENT_REFRESH: "AUTH/SET_SILENT_REFRESH" = "AUTH/SET_SILENT_REFRESH";

export const FETCH_JWT_DATA_REQUEST: "AUTH/FETCH_JWT_DATA_REQUEST" = "AUTH/FETCH_JWT_DATA_REQUEST";
export const FETCH_JWT_DATA_START: "AUTH/FETCH_JWT_DATA_START" = "AUTH/FETCH_JWT_DATA_START";
export const FETCH_JWT_DATA_SUCCESS: "AUTH/FETCH_JWT_DATA_SUCCESS" = "AUTH/FETCH_JWT_DATA_SUCCESS";
export const FETCH_JWT_DATA_FAIL: "AUTH/FETCH_JWT_DATA_FAIL" = "AUTH/FETCH_JWT_DATA_FAIL";

export const SIGN_OUT_REQUEST: "AUTH/SIGN_OUT_REQUEST" = "AUTH/SIGN_OUT_REQUEST";
export const SIGN_OUT_START: "AUTH/SIGN_OUT_START" = "AUTH/SIGN_OUT_START";
export const SIGN_OUT_SUCCESS: "AUTH/SIGN_OUT_SUCCESS" = "AUTH/SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAIL: "AUTH/SIGN_OUT_FAIL" = "AUTH/SIGN_OUT_FAIL";
