// @flow

export const moduleName: string = 'transactions'

export const FETCH_TRANSACTIONS_REQUEST: 'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_REQUEST' =
  'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_REQUEST'
export const FETCH_TRANSACTIONS_START: 'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_START' =
  'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_START'
export const FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_SUCCESS' =
  'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_FAIL: 'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_FAIL' =
  'FETCH_TRANSACTIONS/FETCH_TRANSACTIONS_FAIL'

export const ADD_TRANSACTION_REQUEST: 'ADD_TRANSACTION/ADD_TRANSACTION_REQUEST' =
  'ADD_TRANSACTION/ADD_TRANSACTION_REQUEST'
export const ADD_TRANSACTION_START: 'ADD_TRANSACTION/ADD_TRANSACTION_START' =
  'ADD_TRANSACTION/ADD_TRANSACTION_START'
export const ADD_TRANSACTION_SUCCESS: 'ADD_TRANSACTION/ADD_TRANSACTION_SUCCESS' =
  'ADD_TRANSACTION/ADD_TRANSACTION_SUCCESS'
export const ADD_TRANSACTION_FAIL: 'ADD_TRANSACTION/ADD_TRANSACTION_FAIL' =
  'ADD_TRANSACTION/ADD_TRANSACTION_FAIL'

export const EDIT_TRANSACTION_REQUEST: 'EDIT_TRANSACTION/EDIT_TRANSACTION_REQUEST' =
  'EDIT_TRANSACTION/EDIT_TRANSACTION_REQUEST'
export const EDIT_TRANSACTION_START: 'EDIT_TRANSACTION/EDIT_TRANSACTION_START' =
  'EDIT_TRANSACTION/EDIT_TRANSACTION_START'
export const EDIT_TRANSACTION_SUCCESS: 'EDIT_TRANSACTION/EDIT_TRANSACTION_SUCCESS' =
  'EDIT_TRANSACTION/EDIT_TRANSACTION_SUCCESS'
export const EDIT_TRANSACTION_FAIL: 'EDIT_TRANSACTION/EDIT_TRANSACTION_FAIL' =
  'EDIT_TRANSACTION/EDIT_TRANSACTION_FAIL'

export const DELETE_TRANSACTION_REQUEST: 'DELETE_TRANSACTION/DELETE_TRANSACTION_REQUEST' =
  'DELETE_TRANSACTION/DELETE_TRANSACTION_REQUEST'
export const DELETE_TRANSACTION_START: 'DELETE_TRANSACTION/DELETE_TRANSACTION_START' =
  'DELETE_TRANSACTION/DELETE_TRANSACTION_START'
export const DELETE_TRANSACTION_SUCCESS: 'DELETE_TRANSACTION/DELETE_TRANSACTION_SUCCESS' =
  'DELETE_TRANSACTION/DELETE_TRANSACTION_SUCCESS'
export const DELETE_TRANSACTION_FAIL: 'DELETE_TRANSACTION/DELETE_TRANSACTION_FAIL' =
  'DELETE_TRANSACTION/DELETE_TRANSACTION_FAIL'
