// @flow

export const moduleName: string = "mapCrypto";

export const MAP_CRYPTO_REQUEST: "MAP_CRYPTO/MAP_CRYPTO_REQUEST" = "MAP_CRYPTO/MAP_CRYPTO_REQUEST";
export const MAP_CRYPTO_START: "MAP_CRYPTO/MAP_CRYPTO_START" = "MAP_CRYPTO/MAP_CRYPTO_START";
export const MAP_CRYPTO_SUCCESS: "MAP_CRYPTO/MAP_CRYPTO_SUCCESS" = "MAP_CRYPTO/MAP_CRYPTO_SUCCESS";
export const MAP_CRYPTO_FAIL: "MAP_CRYPTO/MAP_CRYPTO_FAIL" = "MAP_CRYPTO/MAP_CRYPTO_FAIL";
