// @flow

export const moduleName: string = "cryptoInfo";

export const FETCH_CRYPTO_INFO_REQUEST: "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_REQUEST" = "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_REQUEST";
export const FETCH_CRYPTO_INFO_START: "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_START" = "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_START";
export const FETCH_CRYPTO_INFO_SUCCESS: "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_SUCCESS" = "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_SUCCESS";
export const FETCH_CRYPTO_INFO_FAIL: "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_FAIL" = "FETCH_CRYPTO_INFO/FETCH_CRYPTO_INFO_FAIL";
