// @flow

export const moduleName: string = "latestCrypto";

export const LATEST_CRYPTO_REQUEST: "LATEST_CRYPTO/LATEST_CRYPTO_REQUEST" = "LATEST_CRYPTO/LATEST_CRYPTO_REQUEST";
export const LATEST_CRYPTO_START: "LATEST_CRYPTO/LATEST_CRYPTO_START" = "LATEST_CRYPTO/LATEST_CRYPTO_START";
export const LATEST_CRYPTO_SUCCESS: "LATEST_CRYPTO/LATEST_CRYPTO_SUCCESS" = "LATEST_CRYPTO/LATEST_CRYPTO_SUCCESS";
export const LATEST_CRYPTO_FAIL: "LATEST_CRYPTO/LATEST_CRYPTO_FAIL" = "LATEST_CRYPTO/LATEST_CRYPTO_FAIL";
