// @flow

export const moduleName: string = 'cryptoGlobalStats'

export const CRYPTO_GLOBAL_STATS_REQUEST: 'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_REQUEST' =
  'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_REQUEST'
export const CRYPTO_GLOBAL_STATS_START: 'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_START' =
  'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_START'
export const CRYPTO_GLOBAL_STATS_SUCCESS: 'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_SUCCESS' =
  'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_SUCCESS'
export const CRYPTO_GLOBAL_STATS_FAIL: 'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_FAIL' =
  'CRYPTO_GLOBAL_STATS/CRYPTO_GLOBAL_STATS_FAIL'
