// @flow

export const moduleName: string = "cryptoList";

export const FETCH_CRYPTO_LIST_REQUEST: "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_REQUEST" = "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_REQUEST";
export const FETCH_CRYPTO_LIST_START: "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_START" = "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_START";
export const FETCH_CRYPTO_LIST_SUCCESS: "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_SUCCESS" = "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_SUCCESS";
export const FETCH_CRYPTO_LIST_FAIL: "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_FAIL" = "FETCH_CRYPTO_LIST/FETCH_CRYPTO_LIST_FAIL";
