// @flow

export const moduleName: string = "watchlist";

export const INITIAL_WATCHLIST_IDS: "WATCHLIST/INITIAL_WATCHLIST_IDS" = "WATCHLIST/INITIAL_WATCHLIST_IDS";

export const FETCH_WATCHLIST_REQUEST: "WATCHLIST/FETCH_WATCHLIST_REQUEST" = "WATCHLIST/FETCH_WATCHLIST_REQUEST";
export const FETCH_WATCHLIST_START: "WATCHLIST/FETCH_WATCHLIST_START" = "WATCHLIST/FETCH_WATCHLIST_START";
export const FETCH_WATCHLIST_SUCCESS: "WATCHLIST/FETCH_WATCHLIST_SUCCESS" = "WATCHLIST/FETCH_WATCHLIST_SUCCESS";
export const FETCH_WATCHLIST_FAIL: "WATCHLIST/FETCH_WATCHLIST_FAIL" = "WATCHLIST/FETCH_WATCHLIST_FAIL";

export const TOGGLE_WATCHLIST_REQUEST: "WATCHLIST/TOGGLE_WATCHLIST_REQUEST" = "WATCHLIST/TOGGLE_WATCHLIST_REQUEST";
export const TOGGLE_WATCHLIST_START: "WATCHLIST/TOGGLE_WATCHLIST_START" = "WATCHLIST/TOGGLE_WATCHLIST_START";
export const TOGGLE_WATCHLIST_ADDED: "WATCHLIST/TOGGLE_WATCHLIST_ADDED" = "WATCHLIST/TOGGLE_WATCHLIST_ADDED";
export const TOGGLE_WATCHLIST_REMOVED: "WATCHLIST/TOGGLE_WATCHLIST_REMOVED" = "WATCHLIST/TOGGLE_WATCHLIST_REMOVED";
export const TOGGLE_WATCHLIST_FAIL: "WATCHLIST/TOGGLE_WATCHLIST_FAIL" = "WATCHLIST/TOGGLE_WATCHLIST_FAIL";
