// @flow

export const moduleName: string = "watchlist";

export const ADD_WATCHLIST: "WATCHLIST/ADD_WATCHLIST" = "WATCHLIST/ADD_WATCHLIST";

export const TOGGLE_WATCHLIST_REQUEST: "WATCHLIST/TOGGLE_WATCHLIST_REQUEST" = "WATCHLIST/TOGGLE_WATCHLIST_REQUEST";
export const TOGGLE_WATCHLIST_START: "WATCHLIST/TOGGLE_WATCHLIST_START" = "WATCHLIST/TOGGLE_WATCHLIST_START";
export const TOGGLE_WATCHLIST_ADDED: "WATCHLIST/TOGGLE_WATCHLIST_ADDED" = "WATCHLIST/TOGGLE_WATCHLIST_ADDED";
export const TOGGLE_WATCHLIST_REMOVED: "WATCHLIST/TOGGLE_WATCHLIST_REMOVED" = "WATCHLIST/TOGGLE_WATCHLIST_REMOVED";
export const TOGGLE_WATCHLIST_FAIL: "WATCHLIST/TOGGLE_WATCHLIST_FAIL" = "WATCHLIST/TOGGLE_WATCHLIST_FAIL";
