// @flow

export const moduleName: string = "portfolio";

export const FETCH_PORTFOLIO_REQUEST: "FETCH_PORTFOLIO/FETCH_PORTFOLIO_REQUEST" = "FETCH_PORTFOLIO/FETCH_PORTFOLIO_REQUEST";
export const FETCH_PORTFOLIO_START: "FETCH_PORTFOLIO/FETCH_PORTFOLIO_START" = "FETCH_PORTFOLIO/FETCH_PORTFOLIO_START";
export const FETCH_PORTFOLIO_SUCCESS: "FETCH_PORTFOLIO/FETCH_PORTFOLIO_SUCCESS" = "FETCH_PORTFOLIO/FETCH_PORTFOLIO_SUCCESS";
export const FETCH_PORTFOLIO_FAIL: "FETCH_PORTFOLIO/FETCH_PORTFOLIO_FAIL" = "FETCH_PORTFOLIO/FETCH_PORTFOLIO_FAIL";
